apiVersion: skaffold/v3alpha1
deploy:
  cloudrun: {}
kind: Config
metadata:
  name: app
profiles:
  - manifests:
      rawYaml:
        - app-staging.yaml
    name: staging
  - manifests:
      rawYaml:
        - app-prod.yaml
    name: prod
